# Theme style
## normal: index will show articles' excerpt
## plain: index will show archives
theme_style: normal

# meta in head
meta:
  author: Journey1969
  description: Journey1969's Personal Blog
  keywords: Journey1969, Blog, Front-End
  og:
    site_name: Journey1969
    description: Journey1969's Personal Blog
    type:
      article: article

# Header
menu:
  home: /
  archives: /archives
  about: /about

# Content
excerpt_link: true

# Others
favicon: /favicon.ico
