# Theme style
## normal: index will show articles' excerpt
## plain: index will show archives
theme_style: normal

# meta in head
meta:
  author: YOUR_NAME
  description: YOUR_NAME's Blog
  keywords: YOUR_NAME, Blog
  og:
    site_name: YOUR_NAME
    description: YOUR_NAME's Blog
    type:
      article: article

# Header
menu:
  home: /
  archives: /archives
  about: /about

# Content
excerpt_link: true

# Others
favicon: /favicon.ico
