# header nav
home: Home
about: About
archives: Archives

# Index
prev: Prev
next: Next
read_more: Read More

# Post
posted_on: Posted on

# footer
copyright: All Rights Reserved
power_by: Power by
theme: Theme
